bboard/urls.py
from django.urls import path
from bboard.views import index

# from .views import index, by_rubric, BbCreateView, BbDetailView, BbByRubricView
from .views import BbCreateView, BbDetailView, BbByRubricView, BbEditView, BbDeleteView, BbIndexView, \
    BbMonthArchiveView, BbWeekArchiveView

urlpatterns = [
    path('<int:year>/week/<int:week>/', BbWeekArchiveView.as_view(date_field='published')),
    path('<int:year>/<int:month>/', BbMonthArchiveView.as_view()),
    # path('detail/<int:year>/<int:month>/<int:day>/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('add/', BbCreateView.as_view(), name='add'),
    path('edit/<int:pk>/', BbEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),
    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),
    path('', BbIndexView.as_view(), name='index'),
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('bboard.urls')),
    path('bboard/', include('bboard.urls')),
    path('admin/', admin.site.urls),
]

bboard/models.py
from django.db import models
from django.contrib.auth.models import User


class Bb(models.Model):
    title = models.CharField(max_length=50, verbose_name='Товар')
    content = models.TextField(null=True, blank=True, verbose_name='Описание')
    price = models.FloatField(null=True, blank=True, verbose_name='Цена')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
    rubric = models.ForeignKey('Rubric', null=True, on_delete=models.PROTECT, verbose_name='Рубрика')

    #  TODO: изсенить потом прайс на Decimal и добавить поля
    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'
        ordering = ['-published']


class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название')

    class Meta:
        verbose_name_plural = 'Рубрики'
        verbose_name = 'Рубрика'
        ordering = ['name']

    def __str__(self):
        return self.name


class AdvUser(models.Model):
    is_activated = models.BooleanField(default=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

bboard/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm, modelform_factory, DecimalField
from django.forms.widgets import Select

from .models import Bb, Rubric


class RegisterUserForm(forms.ModelForm):
    password1 = forms.CharField(label='Пароль')
    password2 = forms.CharField(label='Пароль(повторно)')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')


class BbForm(forms.ModelForm):
    price = forms.DecimalField(label='Цена', decimal_places=2)
    rubric = forms.ModelChoiceField(queryset=Rubric.objects.all(),
                                    label='Рубрика', help_text='He забудьте задать рубрику',
                                    widget=forms.widgets.Select(attrs={'size': 8}))

    # title = forms.CharField(label=' Название товара')
    # content = forms.CharField(label='Описание', widget=forms.widgets.Textarea())
    # price = forms.DecimalField(label='Цена', decimal_places=2)
    # rubric = forms.ModelChoiceField(queryset=Rubric .objects.all(),
    #                                 label='Рубрика', help_text='He забудьте задать рубрику!',
    #                                 widget=forms.widgets.Select(attrs={'size': 8}))

    class Meta:
        model = Bb
        fields = ('title', 'content', 'price', 'rubric')
        labels = {'title': 'Название товара'}
# BbForm = modelform_factory(Bb,
#                            fields=('title', 'content', 'price', 'rubric'),
#                            labels={'title': 'Название товара'},
#                            help_texts={'rubric': 'Не забудьте выбрать рубрику'},
#                            field_classes={'price': DecimalField},
#                            widgets={'rubric': Select(attrs={'size': 8})}
#                            )


# class BbForm(ModelForm):
#     class Meta:
#         model = Bb
#         fields = ('title', 'content', 'price', 'rubric')
#         labels = {'title': 'Название товара'}
#         help_texts = {'rubric': 'Не забудьте выбрать рубрику'}
#         field_classes = {'price': DecimalField}
#         widgets = {'rubric': Select(attrs={'size': 8})}

bboard/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.views.generic.dates import ArchiveIndexView, MonthArchiveView, WeekArchiveView, DateDetailView
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.list import ListView
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator

from .models import Bb, Rubric
from .forms import BbForm


#
# def by_rubric(request, rubric_id):
#     bbs = Bb.objects.filter(rubric=rubric_id)
#     rubrics = Rubric.objects.all()
#     current_rubric = Rubric.objects.get(pk=rubric_id)
#     context = {'bbs': bbs, 'rubrics': rubrics, 'current_rubric': current_rubric}
#     return render(request, 'bboard/by_rubric.html', context)
#
#

def index(request):
    bbs = Bb.objects.all()
    rubrics = Rubric.objects.all()
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'rubrics': rubrics, 'page': page, 'bbs': page.object_list }
    return render(request, 'bboard/index.html', context)


class BbCreateView(CreateView):
    template_name = 'bboard/create.html'
    form_class = BbForm
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


class BbDetailView(DetailView):
    model = Bb

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


class BbByRubricView(SingleObjectMixin, ListView):
    template_name = 'bboard/by_rubric.html'
    pk_url_kwarg = 'rubric_id'
    # context_object_name = 'bbs'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Rubric.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_rubric'] = self.object
        context['rubrics'] = Rubric.objects.all()
        context['bbs'] = context['object_list']
        return context

    def get_queryset(self):
        return self.object.bb_set.all()

    # def get_queryset(self):
    #     return Bb.objects.filter(rubric=self.kwargs['rubric_id'])
    #
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['rubrics'] = Rubric.objects.all()
    #     context['current_rubric'] = Rubric.objects.get(pk=self.kwargs['rubric_id'])
    #     return context


class BbAddView(FormView):
    template_name = 'bboard/create.html'
    form_class = BbForm
    initial = {'price': 0.0}

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        self.object = super().get_form(form_class)
        return self.object

    def get_success_url(self):
        return reverse('bboard: by_rubric', kwargs={'rubric_id': self.object.cleaned_data['rubric'].pk})


class BbEditView(UpdateView):
    model = Bb
    form_class = BbForm
    success_url = '/'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


class BbDeleteView(DeleteView):
    model = Bb
    success_url = '/'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


class BbIndexView(ArchiveIndexView):
    model = Bb
    date_field = 'published'
    date_list_period = 'year'
    template_name = 'bboard/index.html'
    context_object_name = 'bbs'
    allow_empty = True

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


class BbMonthArchiveView(MonthArchiveView):
    model = Bb
    date_field = 'published'
    month_format = '%m'


class BbWeekArchiveView(WeekArchiveView):
    model = Bb
    date_field = 'published'
    week_format = '%W'

templates/bboard/bb_archive_month.html
{% extends "layout/basic.html" %}
{% load static %}


{% block content %}


    {% for bb in bb_list %}
                    <h2><a href="{% url 'detail' pk=bb.pk %}">{{ bb.title }}</a></h2>


   <p>     {{ bb.content }}</p>
      <p>  {{ bb.price }} руб.</p>

        <p>{{ bb.created_at }}</p>

    {% endfor %}
{% endblock %}

templates/bboard/bb_archive_week.html
{% extends "layout/basic.html" %}
{% load static %}


{% block content %}


    {% for bb in bb_list %}
                    <h2><a href="{% url 'detail' pk=bb.pk %}">{{ bb.title }}</a></h2>


   <p>     {{ bb.content }}</p>
      <p>  {{ bb.price }} руб.</p>

        <p>{{ bb.created_at }}</p>

    {% endfor %}
{% endblock %}

templates/bboard/bb_confirm_delete.html
{% extends 'layout/basic.html' %}
{% block title %}Удаление объявления{% endblock %}

{% block content %}
    <h2>Удаление объявления</h2>
    <p>Рубрика:{{ bb.rubric.name }}</p>
    <p>Товар:{{ bb.title }}</p>
    <p>{{ bb.content }}</p>
    <p>Цена:{{ bb.price }}</p>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
    </form>
{% endblock %}

templates/bboard/bb_detail.html
{% extends 'layout/basic.html' %}

{% block title %}
    {{ bb.title }}
{% endblock %}
{% block content %}
    <p>Рубрика: {{ bb.rubric.name }}</p>
    <h2>{{ bb.title }}</h2>
    <p>{{ bb.content }}</p>
    <p>Цена: {{ bb.price|default:'нет цены' }}</p>

    <a href="{% url 'edit' pk=bb.pk %}">Изменить: {{ bb.title }}</a>
    <a href="{% url 'delete' pk=bb.pk %}">Удалить: {{ bb.title }}</a>
{% endblock %}

templates/bboard/bb_form.html
{% extends 'layout/basic.html' %}
{% block title %}
Исправление объявления
{% endblock %}
{% block content %}
<H1>Исправление объявления</H1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
</form>
{% endblock %}

templates/bboard/by_rubric.html
{% extends 'layout/basic.html' %}
{% block title %}
    {{ current_rubric.name }}
{% endblock %}
{% block content %}
    <h2>Рубрика: {{ current_rubric.name }}</h2>
    {% for bb in bbs %}
{#        {% cycle 'b1' 'b2' as curentclass %} {{ curentclass }}#}
        <div class="{% cycle 'b1' 'b2' %}">
            <h2><a href="{% url 'detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
                    <p>№{{ forloop.counter }}</p>
{#{% firstof bb.phone bb.email 'На деревню дедушке' %}  текст если переменные пустые#}
            <p>{{ bb.content }}</p>
            <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        </div>
    {% endfor %}
{% endblock %}

templates/bboard/create.html
{% extends 'layout/basic.html' %}
{% block title %}
Добавление объявления
{% endblock %}
{% block content %}
<H1>Добавление объявления</H1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

templates/bboard/index.html
{% extends 'layout/basic.html' %}
{% block content %}
    {% with bb_count=bbs.count %}
        {% if bb_count > 0 %}
            <p>Всего {{ bb_count }} объявлений.</p>
        {% endif %}
    {% endwith %}
    {#{% debug %}#}
    {% for bb in bbs %}

        <div>
            <h2><a href="{% url 'detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
            <p>№{{ forloop.counter }}</p>
            <p>{{ bb.content }}</p>
            <p><a href="{% url 'by_rubric' bb.rubric.pk %}">{{ bb.rubric.name }}</a></p>
            <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
            <a href="{% url 'edit' pk=bb.pk %}">Изменить: {{ bb.title }}</a>
            <a href="{% url 'delete' pk=bb.pk %}">Удалить: {{ bb.title }}</a>
            {% for d in date_list %}
                {{ d.day }}
                {{ d.month }}
                {{ d.year }}

            {% endfor %}
        </div>
    {% endfor %}

    {#paginator#}
    <div>
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">&lt;</a>
        {% endif %}
        {{ page.number }} if {{ page.paginator.num_pages }}
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">&gt;</a>
        {% endif %}


    </div>
    {#paginator#}
{% endblock %}